name: CI Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build-backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Backend
        run: dotnet build --no-restore --configuration Release

      - name: Run Backend Tests
        run: dotnet test --no-build --verbosity normal

  build-frontend:
    name: Build and Test Frontend
    runs-on: ubuntu-latest
    needs: build-backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('Website/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install npm dependencies
        working-directory: Website
        run: npm ci

      - name: Lint Code
        working-directory: Website
        run: npm run lint

      - name: Type Check
        working-directory: Website
        run: npm run type-check

      - name: Run Frontend Tests with Coverage
        working-directory: Website
        run: npm test -- --coverage --watchAll=false

      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: Website/coverage/lcov.info
          flags: unittests
          name: codecov-umbrella

      - name: Build Frontend
        working-directory: Website
        run: npm run build

  e2e-tests:
    name: End-to-End Tests
    runs-on: ubuntu-latest
    needs: build-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.18.0'

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('Website/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install npm dependencies
        working-directory: Website
        run: npm ci

      - name: Build Frontend
        working-directory: Website
        run: npm run build

      - name: Start Frontend Server
        working-directory: Website
        run: |
          npm start &
          echo "Waiting for the frontend to be up..."
          npx wait-on http://localhost:3000
        env:
          CI: true

      - name: Run E2E Tests with Cypress
        working-directory: Website
        run: npm run cypress:run
